### ISSUE TITLE
error: [Errno 10061] No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by kv109349** [bitlabstudio/django-registration-email#28]
Hi all,
I want to retrieve information about all the vms running on ESX server. I have found two modules suitable for my requirement. pysphere and psphere. But when I try to connect to the remote server it throws me the following error.
1. psphere:
   URLError: <urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>
2. pysphere:
   error: [Errno 10061] No connection could be made because the target machine actively refused it

Can anyone please help me to resolve this issue. Thanks in advance.

-Vinay Kalyankar.

**Comment by sachinchavan9** [comment]
I have the same issue :(
![mail](https://user-images.githubusercontent.com/27998847/37464604-d2f87a38-287e-11e8-8b54-6abbe2401812.PNG)

how to solve this issue?

**Comment by Tyrdall** [comment]
You need to set up your email connection properly: https://docs.djangoproject.com/en/2.0/topics/email/

**Comment by RoshiniAdapa** [comment]
---------------------------------------------------------------------------
ConnectionRefusedError                    Traceback (most recent call last)
c:\users\roshi\pycharmprojects\djangoml\venv\lib\site-packages\urllib3\connection.py in _new_conn(self)
    158         try:
--> 159             conn = connection.create_connection(
    160                 (self._dns_host, self.port), self.timeout, **extra_kw

c:\users\roshi\pycharmprojects\djangoml\venv\lib\site-packages\urllib3\util\connection.py in create_connection(address, timeout, source_address, socket_options)
     83     if err is not None:
---> 84         raise err
     85 

c:\users\roshi\pycharmprojects\djangoml\venv\lib\site-packages\urllib3\util\connection.py in create_connection(address, timeout, source_address, socket_options)
     73                 sock.bind(source_address)
---> 74             sock.connect(sa)
     75             return sock

ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

NewConnectionError                        Traceback (most recent call last)
c:\users\roshi\pycharmprojects\djangoml\venv\lib\site-packages\urllib3\connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    669             # Make the request on the httplib connection object.
--> 670             httplib_response = self._make_request(
    671                 conn,

c:\users\roshi\pycharmprojects\djangoml\venv\lib\site-packages\urllib3\connectionpool.py in _make_request(self, conn, method, url, timeout, chunked, **httplib_request_kw)
    391         else:
--> 392             conn.request(method, url, **httplib_request_kw)
    393 

~\AppData\Local\Programs\Python\Python38-32\lib\http\client.py in request(self, method, url, body, headers, encode_chunked)
   1239         """Send a complete request to the server."""
-> 1240         self._send_request(method, url, body, headers, encode_chunked)
   1241 

~\AppData\Local\Programs\Python\Python38-32\lib\http\client.py in _send_request(self, method, url, body, headers, encode_chunked)
   1285             body = _encode(body, 'body')
-> 1286         self.endheaders(body, encode_chunked=encode_chunked)
   1287 

~\AppData\Local\Programs\Python\Python38-32\lib\http\client.py in endheaders(self, message_body, encode_chunked)
   1234             raise CannotSendHeader()
-> 1235         self._send_output(message_body, encode_chunked=encode_chunked)
   1236 

~\AppData\Local\Programs\Python\Python38-32\lib\http\client.py in _send_output(self, message_body, encode_chunked)
   1005         del self._buffer[:]
-> 1006         self.send(msg)
   1007 

~\AppData\Local\Programs\Python\Python38-32\lib\http\client.py in send(self, data)
    945             if self.auto_open:
--> 946                 self.connect()
    947             else:

c:\users\roshi\pycharmprojects\djangoml\venv\lib\site-packages\urllib3\connection.py in connect(self)
    186     def connect(self):
--> 187         conn = self._new_conn()
    188         self._prepare_conn(conn)

c:\users\roshi\pycharmprojects\djangoml\venv\lib\site-packages\urllib3\connection.py in _new_conn(self)
    170         except SocketError as e:
--> 171             raise NewConnectionError(
    172                 self, "Failed to establish a new connection: %s" % e

NewConnectionError: <urllib3.connection.HTTPConnection object at 0x0694A880>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

MaxRetryError                             Traceback (most recent call last)
c:\users\roshi\pycharmprojects\djangoml\venv\lib\site-packages\requests\adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    438             if not chunked:
--> 439                 resp = conn.urlopen(
    440                     method=request.method,

c:\users\roshi\pycharmprojects\djangoml\venv\lib\site-packages\urllib3\connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    723 
--> 724             retries = retries.increment(
    725                 method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]

c:\users\roshi\pycharmprojects\djangoml\venv\lib\site-packages\urllib3\util\retry.py in increment(self, method, url, response, error, _pool, _stacktrace)
    438         if new_retry.is_exhausted():
--> 439             raise MaxRetryError(_pool, url, error or ResponseError(cause))
    440 

MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /api/v1/income_classifier/predict?status=ab_testing (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0694A880>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

During handling of the above exception, another exception occurred:

ConnectionError                           Traceback (most recent call last)
<ipython-input-9-3d2c79d2145c> in <module>
      2     input_data = dict(X_test.iloc[i])
      3     target = y_test.iloc[i]
----> 4     r = requests.post("http://127.0.0.1:8000/api/v1/income_classifier/predict?status=ab_testing", input_data)
      5     response = r.json()
      6     # provide feedback

c:\users\roshi\pycharmprojects\djangoml\venv\lib\site-packages\requests\api.py in post(url, data, json, **kwargs)
    117     """
    118 
--> 119     return request('post', url, data=data, json=json, **kwargs)
    120 
    121 

c:\users\roshi\pycharmprojects\djangoml\venv\lib\site-packages\requests\api.py in request(method, url, **kwargs)
     59     # cases, and look like a memory leak in others.
     60     with sessions.Session() as session:
---> 61         return session.request(method=method, url=url, **kwargs)
     62 
     63 

c:\users\roshi\pycharmprojects\djangoml\venv\lib\site-packages\requests\sessions.py in request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
    528         }
    529         send_kwargs.update(settings)
--> 530         resp = self.send(prep, **send_kwargs)
    531 
    532         return resp

c:\users\roshi\pycharmprojects\djangoml\venv\lib\site-packages\requests\sessions.py in send(self, request, **kwargs)
    641 
    642         # Send the request
--> 643         r = adapter.send(request, **kwargs)
    644 
    645         # Total elapsed time of the request (approximately)

c:\users\roshi\pycharmprojects\djangoml\venv\lib\site-packages\requests\adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    514                 raise SSLError(e, request=request)
    515 
--> 516             raise ConnectionError(e, request=request)
    517 
    518         except ClosedPoolError as e:

ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /api/v1/income_classifier/predict?status=ab_testing (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0694A880>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

**Comment by RoshiniAdapa** [comment]
unable to connect can anyone help me in resolving this
